version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: db_9solutions
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  app:
    build: .
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_9solutions
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: urubu100
    restart: unless-stopped

volumes:
  mysql_data:
